apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "key-feed.c3maeqgoumbo.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  ES_HOST: "43.200.112.60"
  ES_PORT: "9200"
  KAFKA_HOST: "43.200.112.60"
  KAFKA_PORT: "9092"